### ISSUE TITLE
Shop Randomly Throws Bug

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#111]
Sometimes when you finish the level and go to open the shop, the game will crash. It's happened to me after I play a few times and on the 2nd or 3rd time finishing the level the game crashes after I click the shop button. This is the error thrown.
![shop bug](https://user-images.githubusercontent.com/18178301/32078846-0a81d5e6-ba6e-11e7-984e-19dc7344058a.PNG)

**Comment by k0d0** [comment]
![image](https://user-images.githubusercontent.com/11823574/32121641-0612b1a0-bb23-11e7-8250-7d0b1aadce4c.png)

Im getting these errors with the same issues. Not sure if this would help narrow it down

**Comment by CoreyNE** [comment]
Should be fixed with latest pull
