### ISSUE TITLE
Health Regens Upon New Level

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#134]
If the shooter takes damage at all during a level, upon continuing onto the next level all health is regained.

**Comment by CoreyNE** [comment]
The reason is health and mana are set to 100 in Shooter. Once a new level is created Shooter is newly created again and health and mana are set to 100 because of the constructor.

**Comment by chasemarley** [comment]
Is this a bug or just a feature? I noticed this too and was thinking that maybe it's fine that for each new level the shooter starts with max health/mana.

**Comment by CoreyNE** [comment]
Feature it is!
