### ISSUE TITLE
Level 3 Bug

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#146]
When you get to level 3 you start below the map and you can't do any controls while an error is thrown.

**Comment by Haseeba09** [comment]
I got a bug fix branch open right no that has the issue solved. Will merge when i get the other bug im chasing solved

**Comment by CoreyNE** [comment]
Yeah I've been looking into it as well

**Comment by CoreyNE** [comment]
Issue is that level 3 doesn't have line: friendFigures.add(shooter); issue is resolved
