### ISSUE TITLE
Terrain Hitbox is Off

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#27]
The left side of the terrain is able to have missiles shot through it going down, though the player still is stopped properly. Here's a screenshot of where it happens. I think the hitbox isn't big enough or isn't centered on it properly.
![screenshot 3](https://user-images.githubusercontent.com/18178301/30753838-26cb73ea-9f86-11e7-8ce4-71ecefcf01bb.png)

**Comment by CoreyNE** [comment]
I've found that it's only the missile that has the problem, so instead of hitbox for terrain its collision detection for the missiles

**Comment by Haseeba09** [comment]
referenced in #61
