### ISSUE TITLE
Missile Doesn't Shoot on Edge of Map

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#29]
The character is unable to shoot when at certain points on the edge of the game map. The bottom of the map is totally fine but the top, left, and right has areas that cause the shooter's missiles to explode as if they are melee. Attached are screenshots of where the effects begin.

**Comment by CoreyNE** [comment]
![left](https://user-images.githubusercontent.com/18178301/30761860-6a1910ac-9fa5-11e7-9e0d-abb8b282b9a5.PNG)

left side where it begins

**Comment by CoreyNE** [comment]
![right](https://user-images.githubusercontent.com/18178301/30761875-71348394-9fa5-11e7-9e3a-94c965e4c7ef.PNG)

right side where it begins

**Comment by CoreyNE** [comment]
![top](https://user-images.githubusercontent.com/18178301/30761881-77c7e44e-9fa5-11e7-8700-3fea772781da.PNG)

top where it begins

**Comment by chasemarley** [comment]
On missile update() method, the dimensions of the screen are static and are going to next state based off old screen size. Dimensions need to be changed, and probably made dynamic for future changes.

**Comment by chasemarley** [comment]
Fixed. Imported window width and height from controller.Main and are using those to dynamically change missile state based off screen size. Closing issue.
