### ISSUE TITLE
Random Exception Thrown When Quitting

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#39]
Randomly when you hit the quit button this exception is thrown. I can't replicate it with 100% success and as of now I think it's random. The game still exits properly as the exception is caught.
![quiterror](https://user-images.githubusercontent.com/18178301/30778814-c267cb40-a0a4-11e7-9eb2-5599e360ad9e.PNG)

**Comment by chasemarley** [comment]
In my testing this seems to happen after you hit start game and then quit. I can't get it to happen if I just run the program and immediately hit the quit button.

**Comment by CoreyNE** [comment]
Yeah I was having the same conclusion. I don't know what triggers it though after starting the game. I've played games where it doesn't throw the exception and other games where it does.
