### ISSUE TITLE
Slow Game Until Melee Enemy Killed

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#62]
For some reason the game runs really slow until you kill the blue melee enemy. I didn't notice it speed up after killing any of the mages and I'm not sure if it's only the blue melee or the red suicide both causing the slow speeds.

**Comment by Haseeba09** [comment]
possibly related to #67 but maybe not. I'll look into this but not sure atm on how to fix

**Comment by Haseeba09** [comment]
resolved with #92
