### ISSUE TITLE
Melee Enemies and Missiles Move Through Part of Terrain

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#64]
In the same way missiles are able to fire through the right half of the terrain and part of the top half of the terrain, melee enemies are able to move through those parts unhindered. I'll attach a screen shot of missiles firing to show where these spots are.

![left](https://user-images.githubusercontent.com/18178301/31290602-b2584674-aa92-11e7-9756-1409787a59ab.PNG)

![top](https://user-images.githubusercontent.com/18178301/31290609-b5664028-aa92-11e7-9b3a-ec3f023807a0.PNG)

**Comment by Haseeba09** [comment]
resolved with #71
