### ISSUE TITLE
Character Doesn't Look Left Properly When Mouse is Below

### ISSUE THREAD

**Issue by CoreyNE** [calebbeats/SHSBDA#65]
The character's sprite doesn't change to facing left properly when the mouse is below him until the pointer is way on the left side. I think the issue is we don't have a down facing sprite. The calculations to face left and right when the mouse is below is the same for when the mouse is above, except it doesn't feel weird when the mouse is above because we have a top facing sprite. I feel we should add a sprite looking down or fix the algorithm when the mouse is underneath the character.

The white dot is where the mouse is. This is where the sprite decides to finally turn left.
![screenshot 1](https://user-images.githubusercontent.com/18178301/31291440-7fa701c2-aa95-11e7-9963-3e2546793aec.png)

The white dot here is where the sprite faces up.
![screenshot 2](https://user-images.githubusercontent.com/18178301/31291459-8ced65ce-aa95-11e7-96ab-32dd723aabb1.png)

**Comment by CoreyNE** [comment]
If this is not explained properly, give me a shout and I'll try to explain it better.

**Comment by k0d0** [comment]
Hung let me know this last night. We did not have a sprite for facing "South" but there is currently one in the SDD as of this morning.

Will leave open until sprite is added.

**Comment by CoreyNE** [comment]
Thanks Kyle. Got it fixed up
